package com.attendease.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4F378A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6750A4)
val md_theme_light_onPrimaryContainer = Color(0xFFE0D2FF)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF9)
val md_theme_light_onSecondaryContainer = Color(0xFF686177)
val md_theme_light_tertiary = Color(0xFF633B48)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7D5260)
val md_theme_light_onTertiaryContainer = Color(0xFFFFCBDA)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFDF8FF)
val md_theme_light_onBackground = Color(0xFF1C1A22)
val md_theme_light_surface = Color(0xFFFDF8FF)
val md_theme_light_onSurface = Color(0xFF1C1A22)
val md_theme_light_surfaceVariant = Color(0xFFE6E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF494551)
val md_theme_light_outline = Color(0xFF7A7582)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFFA)
val md_theme_light_inverseSurface = Color(0xFF312F37)
val md_theme_light_inversePrimary = Color(0xFFCFBCFF)

val SemanticSuccess = Color(0xFF22C55E)
val SemanticWarning = Color(0xFFF59E0B)
val SemanticNeutral = Color(0xFF9CA3AF)
